Likelion-at-SMWU-13th/Spotal-BE

infer/serializers.py, infer/services.py, infer/views.py
- ai요약 정확도 매우 낮음
#26 
---
---
---
---
---
---
=> feat/gpt요약생성 디벨롭

search/service/search.py, search/service/summary_card.py, search/views.py
---
- 가게 검색 시, 사용자 현재 위치 기준으로 검색결과 반환하도록 함
=> Feat : 사용자 gps 기반 검색 추가

search/service/summary_card.py, search/views.py
---
- 요약 카드 생성 시 업태구분명도 반영하도록 추가함
---
=> Feat : 프롬포트에 업태구분명 추가함

recommendations/urls.py, recommendations/views.py
=> feat/ai 요약하는 부분 gpt랑 연결

infer/services.py
#26 
---
---
업태구분을 포함시키지 않아 오류나던 부분 간단 수정
---
---
---
---
=> fix/업태구분 추가

community/ImageSerializer.py
=> Feat : 이미지 url 수정

recommendations/serializers.py, recommendations/views.py
closed #37 
---
---
보관한 장소 조회 시, 더 많은 필드를 응답하도록 수정
코드 오류 개선
---
- 장소보관 기능 관련 코드 오류 개선
- 보관장소 유저별 조회 기능에는 shop 가게 관련 정보 많이 반환하도록 시리얼라이저와 뷰 수정
(원래는 가게 아이디만 반환했었는데, 다음과 같이 가게의 거의 모든 필드가 반환되도록 수정)
---
1. 보관장소 추가 잘 됨 확인
2. 보관장소 조회 잘 됨 확인
3. 보관장소 삭제 잘 됨 확인
4. 그리고 조회할 때는 다음과 같이 shop의 필드를 많이 반환하도록 수정했습니다!
---
---
=> 감정보관함 반환 필드 수정

recommendations/serializers.py, recommendations/views.py
---
---
- 필요없이 중복 응답되던 필드 제거
- 중첩 시리얼라이저였던 걸 -> flat한 응답으로 시리얼라이저 수정
- 가게 추천 로직 구현 이후 감정보관함 기능 제대로 작동하는지 테스트 완료 
---
---
---
---
=> 감정보관함 관련 리팩토링 및 응답 형식 수정

recommendations/apps.py, recommendations/signals.py
closed #72 
closed #23 
---
---
- 사용자 detail 설명 부분 ai 요약 기능 추가
- ai 요약이 생성되는 단위는 북마크 하나입니다! 
즉, 북마크가 삭제될 때 -> 생성
북마크가 생성될 때 -> 생성
입니다.
=> 그렇기 때문에 장소 보관 시 로딩 시간이 조금 걸리게 되었습니다. (물론 1.5초 정도 걸림 그렇게 오래 안 걸림)
마이페이지 조회 시에는 정말 조회만 하기 때문에 로딩시간이 걸린다면 그건 이 이슈 문제는 아니고 다른 이슈 때문일 것입니다.
---
- recommendations 앱에 signals.py 추가 -> SavedPlace 모델이 정의된 곳에 함께 있으면 좋기 때문!!
- signals.py에 ai 요약 기능 관련 서비스 다 넣음
- recommendations/apps.py -> signals 임포트하도록 수정! 
---
---
-> 추후 ai 요약 성능은 개선할 수 있습니다. 
---
=> 마이페이지의 detail AI 사용자 요약 생성하도록 수정

.github/workflows/deploy.yml, .gitignore
#55 
---
---
- 자동 배포 설정
- gitignore 수정
- GitHub Secrets 설정
EC2_HOST: 13.124.195.6
EC2_USERNAME: ec2-user
EC2_SSH_KEY: hackathon_server19.pem 파일 내용 
---
=> Feat : 자동배포 설정

.github/workflows/deploy.yml
=> Feat : 자동화 주소 수정

infer/services.py
=> fix/추천 프롬프트 개선

spotal/settings.py
=> Fix : CORS 추가

recommendations/views.py
=> feat/추천1도 이미지가 잘 뜨도록 하기

recommendations/views.py
=> Feat/추천1 추천로직이 안되는 문제 해결

README.md
=> feat/openai api 디자인 수정, 표 정렬

community/views.py
---
연동 과정 중 생긴 댓글 CRUD 문제 해결
---
=> Feat : 댓글 CRUD 수정

infer/services.py, infer/views.py, recommendations/services/cache_service.py, recommendations/services/emotion_service.py, recommendations/services/google_service.py, recommendations/services/performance_monitor.py, recommendations/views.py, search/service/summary_card.py, spotal/settings.py
#101 
---
---
- **캐싱 시스템 도입**: Google Maps API, GPT API 호출 결과 캐싱
- **처리 개수 제한**: 추천1(8개→5개), 추천2(6개→3개) 가게만 처리
- **성능 모니터링**: 실행 시간 측정 및 로깅 추가
- `recommendations/services/` - 캐싱 서비스 추가
- `infer/services.py` - 캐싱 적용
- `search/service/summary_card.py` - GPT API 캐싱
- `spotal/settings.py` - 캐시 설정 추가
=> Refactor : Google Maps API & GPT API 캐싱 시스템

community/serializers.py, users/views.py
=> Feat: 커뮤니티에 유저 프로필 이미지도 반환하도록 수정

mypage/serializers.py
=> Feat: 마이페이지에서 url 한 번 더 감싸는 문제 해결

community/serializers.py
=> Feat : 게시글 조회 시 보드 id도 반환되도록 수정

community/views.py
=> Feat : 필터링 들여쓰기 수정

community/models.py, community/serializers.py, community/views.py
---
- 게시글 관련 정보 반환 시 해당 게시글에 있는 댓글 수도 반환
---
=> Feat : 게시글 정보 반환 시 댓글 수도 반환하도록 수정
